version: '3.8'

services:
  postgres:
    image: postgres:16-alpine 
    container_name: tido_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" 
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    networks:
      - tido_net

  mongo:
    image: mongo:7.0
    container_name: tido_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./docker_data/mongo:/data/db
    networks:
      - tido_net
networks:
  tido_net:
    driver: bridge